config/routes.rb
SISANPRO::Application.routes.draw do
  root :to => "users#index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customer_services, only: [:show, :index]
  resources :suppliers, only: [:show, :index]
  resources :unity_procons
  resources :faqs
  resources :ratings, only: [:show, :index]
  resources :cdcs

  match '/add_rating', to: 'unity_procons#update'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/allusers', to: 'users#allusers'
  match '/ranking', to: 'unity_procons#ranking'
  match '/faq', to: 'faqs#index'
  match '/cdc', to: 'cdcs#index'
  match '/avaliar', to: 'ratings#index'

  get "/graphs", to: 'customer_services#graphs'

  get '/list', to: 'customer_services#list'
  get "/customer_service/filter_customer_service_by_type", to: "customer_services#filter_customer_service_by_type"
  get "/customer_service/filter_customer_service_by_type_region", to: "customer_services#filter_customer_service_by_type_region"
  get "/customer_service/custom_search", to: "customer_services#custom_search"
  get "/customer_service/index", to: "customer_services#index"
  get "/unity_procon/custom_search", to: "unity_procons#custom_search"
  get "/supplier/custom_search", to: "suppliers#custom_search"
  get "/unity_procon/custom_search_ranking", to: "unity_procons#custom_search_ranking"

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email_user, :name_user, :password, :password_confirmation, :address_user
	has_secure_password
	after_validation { self.errors.messages.delete(:password_digest) }
	before_save { |user| user.email_user = email_user.downcase }
	before_save :create_remember_token
#	list_ratings = Array.new
	has_many :ratings


	validates :name_user, presence: true, length: { maximum:50 }
	validates :address_user, presence: true, length: { maximum:2 }
	validates :email_user, length: { maximum:70 }
 	valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email_user, format: { with: valid_email_regex },
  			   uniqueness: { case_sensitive:false }
  	validates :password, length: { minimum: 6}, allow_blank: true


	  def User.new_remember_token
	    SecureRandom.urlsafe_base64
	  end

	  def User.digest(token)
	    Digest::SHA1.hexdigest(token.to_s)
	  end

  	private

  	def create_remember_token
	      self.remember_token = SecureRandom.urlsafe_base64
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def allusers
		@users = User.all
	end

	def index
		@user = User.all
	end

	def new
		@user = User.new
	end

	# Create and associate one user to one id.

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			flash[:sucess] = "Seja bem-vindo!"
			redirect_to :action => :show, :id => @user.id
		else
			render 'new'
		end
	end

	# Show one especific user.
	def show
		@user = User.find(params[:id])
	end

	# Edit one user.
	def edit
		@user = User.find(params[:id])
		if !signed_in? || current_user != @user
			redirect_to root_path
			flash[:danger] = "Esta conta nao e sua."
		end
	end

	# Update one edited user.
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:sucess] = "Usuario editado com exito!"
			sign_in(@user)
			redirect_to @user
		else
			render 'edit'
		end
	end

	# delete one user.
	def destroy
		@user = User.find(params[:id])
		if current_user != @user
			redirect_to root_path
			flash[:error] = "Esta conta nao e sua."
		else
			@user.destroy
			redirect_to root_path
			flash[:sucess] = "Usuario excluido com exito."
		end
	end

  private

	def user_params
	params.require(:user).permit(:name_user, :email_user,
						:address_user, :password_confirmation,
						:password)
	end
end

app/views/users/_signup_fields.html.erb
<%= render 'shared/error_messages' %>

<%= f.label :name_user, "Nome" %></br>
<%= f.text_field :name_user %></br>

<%= f.label :email_user, "E-mail" %></br>
<%= f.text_field :email_user %></br>

<%= f.label :password, "Senha" %></br>
<%= f.password_field :password %></br>

<%= f.label :password_confirmation, "Repetir" %></br>
<%= f.password_field :password_confirmation %></br>

<%= f.label :address_user, "Estado" %></br>
<%= f.select :address_user, options_for_select([["AC", "AC"], ["AL", "AL"], ["AP", "AP"], ["AM", "AM"],
  ["BA", "BA"], ["CE", "CE"], ["DF", "DF"], ["ES", "ES"], ["GO", "GO"], ["MA", "MA"], ["MT", "MT"],
  ["MS", "MS"], ["MG", "MG"], ["PR", "PR"], ["PB", "PB"], ["PA", "PA"], ["PE", "PE"], ["PI", "PI"],
  ["RJ", "RJ"], ["RN", "RN"], ["RS", "RS"], ["RO", "RO"], ["RR", "RR"], ["SC", "SC"], ["SE", "SE"],
  ["SP", "SP"], ["TO", "TO"]]) %></br></br>

app/views/users/allusers.html.erb
<% provide(:title, "Usuários") %>
<title><%= yield(:title) %></title>
<h1>
	Lista de usuários registrados:</br>
</h1>
<h2>
	<% @users.each do |user| %>
    <tr>
      <td><%= user.name_user %></td>, id: <%= user.id %></br>
    </tr>      
	<% end %>
</h2>

app/views/users/destroy.html.erb
<% provide(:title, "Usuário deletado") %>
<title><%= yield(:title) %></title>
  <center><h1>
  Usuário Excluído </br>
  <%= link_to "Logar", signin_path %></br>
  <%= link_to "Home", root_path %></br>
  </h1></center>

app/views/users/edit.html.erb
<% provide(:title, "Editar perfil") %>
<title><%= yield(:title) %></title>
<%= form_for(@user) do |f| %>
	<center>
	  <%= render 'shared/error_messages' %><br>
	  <h1><%= @user.name_user %> - Editando Conta</h1></br>
	  <%= f.label :address_user, "Mudar Estado:" %></br>
	  <%= f.select :address_user, options_for_select([[@user.address_user, @user.address_user], ["AC", "AC"], ["AL", "AL"], ["AP", "AP"], ["AM", "AM"], ["BA", "BA"], ["CE", "CE"], ["DF", "DF"], ["ES", "ES"], ["GO", "GO"], ["MA", "MA"], ["MT", "MT"], ["MS", "MS"], ["MG", "MG"], ["PR", "PR"], ["PB", "PB"], ["PA", "PA"], ["PE", "PE"], ["PI", "PI"], ["RJ", "RJ"], ["RN", "RN"], ["RS", "RS"], ["RO", "RO"], ["RR", "RR"], ["SC", "SC"], ["SE", "SE"], ["SP", "SP"], ["TO", "TO"]]) %>
	  <br><br>

	  <%= f.label :email_user, "Mudar E-mail:" %></br>
	  <%= f.text_field :email_user %></br>
	  <br>


	  <%= f.label :password, "Mudar Senha:" %></br>

	  <%= f.password_field :password %></br>
	  <br>

	  <%= f.submit "Salvar mudanças", class: "btn btn-large btn-primary" %>
	</center>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "Seja Bem-vindo!") %>
<title><%= yield(:title) %></title>
<center>
	<div class="span12">
		<br><br><br><br><br><br><br>
		<img src="/assets/LogoComSombra.png">
		<br>
		<img src="/assets/NomeLogo.png">
		<h1>	
		<% if signed_in? %>
			<h1>Seja bem-vindo,  <%= current_user.name_user %>.</h1>
		<% else %>
			Novo? <%= link_to "Registre-se!", signup_path %></br>
			<%= link_to "Logar", signin_path %></br>
		<% end %>
		</h1>
	</div>
</center>

app/views/users/new.html.erb
<div class="center jumbotron">
	<% provide(:title, "Cadastro de novo usuário") %>
	<title><%= yield(:title) %></title>
	<h1>Cadastro de Usuário</h1>

	<%= form_for(@user) do |f| %>
		<%= render 'signup_fields', f: f %>
		<%= f.submit "Registrar conta", class: "btn btn-large btn-primary" %>
	<% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name_user) %>
<title><%= yield(:title) %></title>

<p align="justify">
	<div style="padding-left: 50px; border:1px solid #999; -webkit-border-radius:4px; -moz-border-radius:4px; border-radius:4px; min-height:20px; padding:19px;">
		<h2>
		<font face="verdana" color="gray">Nome:</font> <span style="padding-left: 11px;"><%= @user.name_user %></br></span>
		<font face="verdana" color="gray">Estado:</font> <%= @user.address_user %></br>
		<font face="verdana" color="gray">E-Mail:</font> <span style="padding-left: 10px;"><%= @user.email_user %></br></span>
		<font face="verdana" color="gray">ID:</font> <span style="padding-left: 62px;"> <%= @user.id %></br></span>
		</h2>
	</div>	
	<h1>
	<% if current_user == @user %>
    	<div class="span1"  style="position: absolute">
    	<%= button_to "Editar", edit_user_path, :class => "btn btn-large btn-primary", :method => :get %>
    	</div>
    	<div class="span1"  style="padding-left: 70px;">
    	<%= button_to "Deletar", user_path, :class => "btn btn-large btn-primary", :method => :delete, data: { confirm: "Você tem certeza?"} %>
    	</div>
	<% end %>
	</h1>
</p> 

app/views/users/update.html.erb
<h1>Nome: <%= @user.name_user %></br>
	Estado: <%= @user.address_user %></br>
	ID: <%= @user.id %></br>
</h1>