config/routes.rb
SISANPRO::Application.routes.draw do
  root :to => "users#index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :customer_services, only: [:show, :index]
  resources :suppliers, only: [:show, :index]
  resources :unity_procons
  resources :faqs
  resources :ratings, only: [:show, :index]
  resources :cdcs

  match '/add_rating', to: 'unity_procons#update'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/allusers', to: 'users#allusers'
  match '/ranking', to: 'unity_procons#ranking'
  match '/faq', to: 'faqs#index'
  match '/cdc', to: 'cdcs#index'
  match '/avaliar', to: 'ratings#index'

  get "/graphs", to: 'customer_services#graphs'

  get '/list', to: 'customer_services#list'
  get "/customer_service/filter_customer_service_by_type", to: "customer_services#filter_customer_service_by_type"
  get "/customer_service/filter_customer_service_by_type_region", to: "customer_services#filter_customer_service_by_type_region"
  get "/customer_service/custom_search", to: "customer_services#custom_search"
  get "/customer_service/index", to: "customer_services#index"
  get "/unity_procon/custom_search", to: "unity_procons#custom_search"
  get "/supplier/custom_search", to: "suppliers#custom_search"
  get "/unity_procon/custom_search_ranking", to: "unity_procons#custom_search_ranking"

end

app/views/layouts/_footer.html.erb
<div class="panel-footer footer" id="footer">
	<span style="color:#FFA500">
		<center>Todos os direitos Reservados</center>
	</span>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<a class="brand" href= '/'+root_path ><img src="/assets/PROCONSULTA.png"></a>
		<div class="container">
			<ul class="nav pull-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Avaliar Procon", avaliar_path %></li>
				<li id="fat-menu" class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Dados <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "Atendimentos", customer_services_path %></li>
					<li><%= link_to "Fornecedores", suppliers_path %></li>
					<li><%= link_to "Ranking de Unidades do Procon", '/ranking' %></li>
					<li><%= link_to "Unidades do Procon", unity_procons_path %></li>
				</ul>

				<li><%= link_to "Gráficos", graphs_path %></li>
				<li><%= link_to "Legislação", cdcs_path %></li>
				<li><%= link_to "FAQ", faqs_path %></li>

				<% if signed_in? %>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<%= current_user.name_user %> <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Conta", current_user %></li>
							<li class="divider"></li>
							<li>
							<%= link_to "Deslogar", signout_path, method: "delete" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						Acesso <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Registrar", signup_path %></li>
							<li><%= link_to "Login", signin_path %></li>
						</ul>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta charset="utf-8">
<html>
	<% provide(:title, ' - Proconsulta') %>
	<title><%= yield(:title) %></title>
	<body id="grad">
		<head>
			<%= stylesheet_link_tag "custom" %>
			<%= stylesheet_link_tag    "application", media: "all" %>
			<%= javascript_include_tag "application" %>
			<%= javascript_include_tag "//www.google.com/jsapi" %>
			<%= javascript_include_tag "path/to/highcharts.js", "chartkick" %>

			<%= csrf_meta_tags %>
			<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
		</head>

		<%= render 'layouts/header' %>
		<%= render 'layouts/shim' %>

		<div class="container" id="yield-container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</div>
	</body>

	<%= render 'layouts/footer' %>

</html>